### ISSUE TITLE
Change logging structure for cobra commands

### ISSUE THREAD

**Issue by shrutiparabgoogle** [apigee/registry#243]
Currently, all the cobra commands implement the `Run()` function which executes the the command's main functionality and doesn't return anything. All the commands also log using the standard log library which print's to stdout.

With the introduction of `resolve` command command, we have essentially wrapped all the existing commands in the `resolve` command. `resolve` will call the sub-commands like `lint`, `complexity` or any other `registry` command using `cmd.Execute()` function.

Currently, there is no way to capture the output or error produced by the underlying subcommand. Looking at logs will still give us the error or output in stdout,  however, when `resolve` command is executing a bunch of sub-commands in parallel, we would like more control over the output and error produced by each sub-command so that we can organize the logs for `resolve` command better. 

This will also help in deriving better log based metrics.

**Comment by shrutiparabgoogle** [comment]
One option is to pass a buffer to write output and error.

Using [cmd.SetOut()](https://pkg.go.dev/github.com/spf13/cobra#Command.SetOut) the resolve command can pass a buffer to capture output and error. Then each command and use [cmd.OutOrStdout](https://pkg.go.dev/github.com/spf13/cobra#Command.OutOrStdout) and [cmd.OutOrStdErr](https://pkg.go.dev/github.com/spf13/cobra#Command.OutOrStderr) to write error and output messages.

This will require a change across all cobra commands.

**Comment by shrutiparabgoogle** [comment]
cc @seaneganx And a related issue: https://github.com/apigee/registry/issues/231

**Comment by seaneganx** [comment]
We might be able to connect the logger to the command's output writer using the [log package's SetOutput function](https://pkg.go.dev/log#SetOutput). If we're working with multiple commands we might have to make sure they're all logging to the same buffer, or somehow manage separate logger instances for each cobra command.

I'm wary of trying to read the output from these buffers to figure out what happened while the command executed. Detecting whether an error occurred seems reasonable though, and I think we should be able to reliably achieve that without reading the output. 

For example, if we were using multiple processes, [os/exec](https://pkg.go.dev/os/exec) should be able to reliably tell us if the action was successful, and also gives us full control over the output pipes.

**Comment by shrutiparabgoogle** [comment]
I explored the options for the following two approaches:

1) Reading output of subcommand, let resolve aggregate all the output from the subcommand and log as one message. Generate metrics from this singular log message. Metrics will include the raw output generated by subcommand, action taken, and success/failure status (derived from the *exec.ExitError)

2) Prefixing the output of subcommands with a unique ID (for each task) and let the subcommands log the messages. Here, the metrics can be derived by grouping messages from the taskID together. There will be more effort on the logging/metrics query side, grouping based on taskIDs and deriving error/output from the level of error messages. Ideally, the way this would want to work is getting all the logs together for a particular taskID, grouping them into error and log messages. This will also require some control over the logger of the subcommand to append a prefix to it. 

While the second approach seems ideal (letting each command log it's own output), this will require advanced logging practices (like logging to different levels and ability to control subCommand logs) followed throughout the codebase. And possibly developing a common logging util. First approach seems like a good short term solution which does the job for basic metrics.

@seaneganx what are your thoughts on this? Also, do you know what will be the priority of this https://github.com/apigee/registry/issues/231 issue, we can target the second approach based on when we plan to revisit the logging mechanism in the codebase.

**Comment by shrutiparabgoogle** [comment]
Looking more into this, I realized that the aggregate functions available right now in [MQL](https://cloud.google.com/monitoring/mql/reference#aggr-function-group) supported by GCP are more focused on numeric values. 

There is no function currently which can take in all the string values in a group and concatenate them to display the aggregated value. This functionality will be required for approach no. 2 to group multiple log entries based on TaskIDs and display the output/error messages.

**Comment by seaneganx** [comment]
>Reading output of subcommand, let resolve aggregate all the output from the subcommand and log as one message.  Generate metrics from this singular log message. Metrics will include the raw output generated by subcommand, action taken, and success/failure status (derived from the *exec.ExitError)

If I'm understanding correctly, the main idea for this approach is to have the parent task reading the logs of the child action to generate extra info ("action taken" and success/failure status) that can be printed out. Writing all of the child command's logs as a single message isn't necessary to achieve this.

For example, we can use a MultiWriter to write the child's logs to stdout _and_ to a buffer for reading and generating metrics. This probably requires write synchronization on the stdout writer though, since each child process will be writing concurrently to the same output.

>Prefixing the output of subcommands with a unique ID (for each task) and let the subcommands log the messages. Here, the metrics can be derived by grouping messages from the taskID together. There will be more effort on the logging/metrics query side, grouping based on taskIDs and deriving error/output from the level of error messages.

When are the metrics generated? The parent can have direct access to its child command's logs as I described above, so we may not need to group by task ID at that moment. If we're generating this information after running the `resolve` command and receiving interleaved output logs, then we will need to take other approaches to filtering. 

>Ideally, the way this would want to work is getting all the logs together for a particular taskID, grouping them into error and log messages. This will also require some control over the logger of the subcommand to append a prefix to it.

We can easily add a unique prefix to the logger for every command we execute, which will let us separate them even when they're interleaved with other task outputs. Until we refactor our logging to add more structure, I don't think we can separate errors from other log messages since they have the same format and print to the same location.

>Also, do you know what will be the priority of this #231 issue, we can target the second approach based on when we plan to revisit the logging mechanism in the codebase.

I can work on this sooner if we think it's valuable here. If we know which features specifically we want, then I can come up with a better estimate of how long it will take. For example, adding a random prefix to logs for each process will be easy. Using separate prefixes for each task within a process will be more difficult. Adding relationship information after that would also be difficult, e.g. being able to identify the parent's log ID using a child's log ID.

>There is no function currently which can take in all the string values in a group and concatenate them to display the aggregated value. This functionality will be required for approach no. 2 to group multiple log entries based on TaskIDs and display the output/error messages.

Why do we need to use aggregation functions for this? Filtering by task ID seems more appropriate, but I might be misunderstanding the situation. When would we use MQL to examine our output, and what do we want to do with it? This is the first I'm hearing about it.

**Comment by shrutiparabgoogle** [comment]
With the new structured logging approach, we can now do the following:
* Pass a flag. --taskID for 1p task executions. The logger of the 1p `registry` command will attach the taskID in the logs.
* Create a custom logger which adds the taskID information in the logs. Route the logs generated by the 3p task executions through this custom logger to include the necessary information in the logs.
