### ISSUE TITLE
Registry API: Transactional database operations

### ISSUE THREAD

**Issue by seaneganx** [apigee/registry#448]
### Background

Most of our API methods perform several database operations. For example, the `UpdateApi` method reads the API first to make sure it exists and to load its current state, then applies any necessary changes in memory before writing back the API's updated state. Deletions have already been updated to use transactions in #434. 

Currently most of our API methods execute their necessary database operations using multiple transactions. This causes race conditions as discussed in #382, although using transactions may not solve other race conditions that might exist in the registry tool.

### Ideas

I think the ideal approach to this is to modify the interface exported by the `storage` package so each API method only interacts with the database once per request. Each interaction would be completed in one transaction.

Any other ideas I can think of seem like they would be messy and/or difficult to maintain.

**Comment by timburks** [comment]
This is largely addressed by #706. However, because the transactions group write operations only, it is still possible to have races that occur between reads and updates. In #715, [we discussed the possibility of tightening the transaction locks](https://github.com/apigee/registry/pull/715#issuecomment-1234494283). We might also rewrite our update methods to only modify the fields specified in the request, eliminating the need for the initial get.

**Comment by timburks** [comment]
See #720 for a stronger approach that does not rely on retry and that also prevents the read-modify-write races that could occur when updating existing resources. It uses full-table locks, which are probably only necessary for the `allow_missing` case (when no row initially exists), and so if performance seems to be a problem, we might refine this with single-row locks for rows that already exist.

**Comment by theganyo** [comment]
I think this can probably be closed with https://github.com/apigee/registry/pull/760.
