### ISSUE TITLE
Registry Server: Improve the performance of ListApis

### ISSUE THREAD

**Issue by giteshk** [apigee/registry#492]
The response time of the ListApis gets progressively worse with the increate in the number of APIs.

This is because we fetch all the rows and then apply the filters.

Improving this API call will have positive effects on the usability of this project.

some initial benchmark results for a setup with Registry server running on GKE with Cloud Postgresql

| Number of APIs | Number of Versions|Response time in ms/op|
|-|-|-|
|100|1|160|
|500|1|300|
|1000|1|436|
|2500|1|864|
|100|3|69|
|500|3|270|
|1000|3|418|
|2500|3|885|

**Comment by seaneganx** [comment]
Is there much variation in performance between runs? I'm surprised to see a 70% difference in response time for Listing APIs when they have a different number of versions. It's surprising because we don't read the versions table at any point during a ListAPIs call.

With larger numbers of APIs the performance seems to stabilize, reducing from 70% (100 APIs) to 11% (500 APIs) to 4% (1000 APIs) to 2% (2500 APIs). This makes me suspicious of the accuracy for those measurements with lower API counts. What happens if we run the benchmarks multiple times and average the results?

**Comment by seaneganx** [comment]
>For the Listing API call with no Filters the page size was set to (Number of APIs)/10

I'm concerned about how meaningful our results are when we have so many variables in the benchmarks. Increasing the page size likely causes a decrease in performance per call, and so does increasing the number of specs. If we see a decrease, how do we know which variable is causing it? IMO this page size should be constant - either a configurable constant if we want to measure the effect of increasing page sizes, or a fixed constant if we don't.

**Comment by giteshk** [comment]
Agreed.. I  changed the page size to **20** last week after for the benchmark tests to ensure the only variable is the number of API Specs.  Thanks for pointing this out.
