### ISSUE TITLE
refactor: move /connection to /pkg/connection

### ISSUE THREAD

**Issue by theganyo** [apigee/registry#651]
See #625

**Comment by seaneganx** [comment]
Looks like this change broke some dependencies in apigee/registry-experimental. Currently things are working fine because registry-experimental is pinned to [v0.4.2](https://github.com/apigee/registry-experimental/blob/fb10477035075e42a77275d3a464f85119162bb4/go.mod#L10). I think we can tag new versions safely, but we won't be able to upgrade registry-experimental to use these new `pkg/` packages until everything is wired correctly.

**Comment by theganyo** [comment]
I'll take a look, thanks.
