### ISSUE TITLE
Registry server: sqlite "database is locked" errors are reported as Internal

### ISSUE THREAD

**Issue by timburks** [apigee/registry#666]
While running some parallel wipeout tests with the sqlite backend, I get errors like this:
```
 FATAL[0021] Task failed: delete projects/hosted-ci-test/locations/global/apis/my-api/versions/v037 error=rpc error: code = Internal desc = database is locked
```
That's described in more detail [here](https://github.com/mattn/go-sqlite3/issues/274), and I think it would be appropriate to return a retriable error code in this case, such as [Unavailable](https://github.com/grpc/grpc-go/blob/64174955202ffb5ea4122e25d1aaece49cc5a3ed/codes/codes.go#L180).

**Comment by timburks** [comment]
I think we should be checking [here](https://github.com/apigee/registry/blob/2c94ac7bf013279f5c9747c2b6bc37587181a189/server/registry/internal/storage/delete.go#L43) among other places in the same file.

**Comment by seaneganx** [comment]
Some potentially relevant documentation.

http://sqlite.com/matrix/rescode.html#busy

>The SQLITE_BUSY result code differs from [SQLITE_LOCKED](http://sqlite.com/matrix/rescode.html#locked) in that SQLITE_BUSY indicates a conflict with a separate [database connection](http://sqlite.com/matrix/c3ref/sqlite3.html), probably in a separate process, whereas [SQLITE_LOCKED](http://sqlite.com/matrix/rescode.html#locked) indicates a conflict within the same [database connection](http://sqlite.com/matrix/c3ref/sqlite3.html) (or sometimes a database connection with a [shared cache](http://sqlite.com/matrix/sharedcache.html)).

With the wipeout command we make lots of concurrent requests to the server, but the server only uses one database client per request. That said, we would expect a conflict with a separate database connection (SQLITE_BUSY) instead of one within the same connection (SQLITE_LOCKED). https://github.com/mattn/go-sqlite3/issues/274 seems to be focused on the SQLITE_BUSY error too.

It's possible we're running into the following variant of this error.

http://sqlite.com/matrix/rescode.html#busy_snapshot

>The following scenario illustrates how an SQLITE_BUSY_SNAPSHOT error might arise:
>
>1. Process A starts a read transaction on the database and does one or more SELECT statement. Process A keeps the transaction open.
>2. Process B updates the database, changing values previous read by process A.
>3. Process A now tries to write to the database. But process A's view of the database content is now obsolete because process B has modified the database file after process A read from it. Hence process A gets an SQLITE_BUSY_SNAPSHOT error.

I'll see if I can reproduce the issue using a similar setup to what's described in that documentation, and if I can reproduce it, I'll see if handling that error fixes the issue.
