### ISSUE TITLE
Registry conformance tool: Add support for gzipped protos

### ISSUE THREAD

**Issue by shrutiparabgoogle** [apigee/registry#800]
The conformance command code only check for `zipped` protos and not `gzip`:
https://github.com/apigee/registry/blob/main/cmd/registry/conformance/conformance-task.go#L106

This results in failure to report accurate conformance reports for gzip protos, add another check for gzip mimeType and handle the bundle accordingly before writing the contents to the file.

**Comment by shrutiparabgoogle** [comment]
The protos were uploaded using the following command:
```
tar cvzf apigeeregistry_protos.tar.gz google/cloud/apigeeregistry
```

From what I understand our current support for [UnGzipping](https://github.com/apigee/registry/blob/main/cmd/registry/core/gzip.go) cannot handle gzipped archives, it can only handle gzip compressed individual files. Make sure that we handle the gzipped protos and document clearly the recommended ways of compressing and uploading the proto files.

@timburks I might need some help with this.

**Comment by timburks** [comment]
As we discussed, I'd like to lower the priority of this significantly (I'll tag it "wont fix" but am open to discussion). We currently have  a way to upload collections of files (zip archives), and adding a second burdens downstream tools with the need to support both. I don't think adding a second archive method adds any functional value.

I think this problem may have appeared because there was confusion about the uploadable mime types in an application UI. I think clarifying that would be the best way to resolve this.
