### ISSUE TITLE
Registry tool: flatten `bulk` out of `registry upload` and bring subcommands up.

### ISSUE THREAD

**Issue by timburks** [apigee/registry#926]
After #925 is merged, the `registry upload` subcommand will consist of `csv` and the bulk uploaders. With `registry apply` becoming our recommended mechanism for adding information to the registry, I think it would be reasonable to treat the `registry upload` subcommands as an opinionated set of special case handlers, and that it would make sense to have `csv` alongside `discovery`, `openapi`, and `proto`. It wouldn't be hard to argue that `csv` is also a bulk uploader, so there's not much conceptual difference among these commands -- all are opinionated uploaders that simplify special-case situations that we think are noteworthy enough to directly support.

@theganyo @seaneganx @giteshk - thoughts?

**Comment by seaneganx** [comment]
IMO we should have simple well-rounded tools that do one thing and can be easily connected with each other. All of these "uploaders" could be pushing information through `registry apply` instead of independently integrating with the API and taking the extra responsibility of uploading info. The important thing about those uploaders isn't that they upload - it's that they take a data source and pull all the information that can be stored in the registry.

Not trying to start a discussion about naming or what kinds of commands belong in the `registry` tool, but imagine a command `registry extract (csv|openapi|discovery|proto|...)` that pulls all the relevant information from different data sources and turns it into something that can be pushed up with `registry apply`. 

Could we run `registry extract csv /path/to/csv | registry apply` to push up all the specs from a CSV file? Or maybe we want to review the YAML before pushing it up using `registry extract csv /path/to/csv --out=/path/to/output/dir`.

**Comment by timburks** [comment]
@seaneganx yes, that's a reasonable refactoring - at times I've thought that all of these uploaders should move to `registry-experimental`, where they would do something like what you described: prepare a directory of YAML and related files that could be applied. I don't think it's time to do that just yet because 1) it's a largish amount of work and 2) keeping the uploaders in `registry` makes distribution easier, and they provide easy onramps for people to try a populated registry.

If you don't mind, let's discuss that refactor in a longer-term issue and keep this one scoped to the rename, which seems like a good next step.

**Comment by seaneganx** [comment]
Agreed. And regarding the actual issue: flattening sounds fine to me.
