### ISSUE TITLE
Registry tool: What are the limitations of `registry apply`?

### ISSUE THREAD

**Issue by seaneganx** [apigee/registry#984]
#880 seems to add a check that rejects any `--parent` values that don't match `projects/{project}/locations/{location}`. 

1. Does `registry apply` only accept hierarchies of resources with an API at the root?
2. Can I use `registry apply` to create a Spec without overwriting its parent API and Version?

Creating this issue so we can discuss the limitations and turn it into documentation.

**Comment by timburks** [comment]
We might need an in-person discussion but here are some thoughts:
- `registry apply` is work in progress and limitations that exist now might be improvements that we decide to make.
- `registry apply` accepts YAML for any resource. Non-top-level resources *must* fully-specify their `parent` in `metadata`.
- The `--parent` option of `registy apply` is a misnomer. This should be `--project` but I think we got caught up in pedantry over the differences between project ids, project names, and location names. With some hindsight, I think we should just have a `--project` option that liberally accepts at least `projects/myproject` and `projects/myproject/locations/global` and probably also `myproject`. We should do this same thing for uploaders and other commands that need a project (and note that project can be set in configuration).
- Yes, it is currently possible to create specs (or any other non-top-level-resource) without touching the parent API or version. Just apply a YAML description of the spec itself with its `metadata.parent` set appropriately.

**Comment by seaneganx** [comment]
I think the key piece of info I was missing was the `metadata.parent` field. When I was trying to figure it out I looked in a few places and didn't find any examples of it.

1) The documentation from `registry apply --help`. I saw the wiki link but didn't open it.
2) The tests for `registry apply` found at `cmd/registry/cmd/apply`.
3) The documentation for `registry` found at `cmd/registry`.

Now I see the tests in `cmd/registry/patch/` and the wiki entry for `registry apply` have the info I needed. We can probably do a better job of surfacing this info. Some ideas:

* Better documentation on the command itself. Linking directly to https://github.com/apigee/registry/wiki/registry-apply would be much more engaging than the generic wiki link at the bottom of the output.
* More usage examples in the wiki. At least: 1) Applying an API resource, 2) Applying a resource to a given parent 3) Applying a resource and children, 4) Applying a collection of resources.

Questions about the "registry object" terminology:
* Is the entire YAML file a registry object?
* Is everything with an `apiVersion` field a registry object?
* Is everything with a `kind` field a registry object? Collections/lists don't have a `kind` field.
* When an `API` includes sub-resources in its `data` field, is the entire hierarchy a registry object? 
* When an `API` includes sub-resources in its `data` field, is each sub-resource a registry object?

**Comment by seaneganx** [comment]
Updated the wiki: [Diff from previous revision](https://github.com/apigee/registry/wiki/registry-apply/_compare/9bf97998ba8056eb69879eb9c60a8d03c5bed58c...99d864190dc9d15244acbc4212a0864f3022e4b0).

**Comment by timburks** [comment]
"Registry Object" was to align with Kubernetes, and if not for that, these might have just been called "Registry Resources", but now reviewing the Kubernetes docs, I see "Kubernetes objects are persistent entities in the Kubernetes system."

What we are instead describing is a YAML format for representing one or more resources in a registry, and Kubernetes doesn't seem to have a name for the format. It's just described by "Describing a Kubernetes object"

So "Registry Resource Description" would be more accurate and might be the better name to use. Unfortunately it's a tongue-twister.

Let's continue to use "registry object" for now and then discuss an alternate name.

We might start by saying that "a registry object is a YAML representation of one or more registry resources that can be applied with 'registry apply`." Based on that...

> Is the entire YAML file a registry object?

yes, but...

> Is everything with an apiVersion field a registry object?

... there must be an apiVersion field, at least at the top level so that `registry apply` knows to read this file. It should be ok to run `registry apply -f . -R` in directories that contain other YAML files that aren't "ours".

> Is everything with a kind field a registry object? Collections/lists don't have a kind field.

Yes... I was initially planning to require lists to have a kind field but saw that lists returned by kubectl don't have them. So the presence of `items` identifies a list, and it should probably be an error to have both `kind` and `items`.

> When an API includes sub-resources in its data field, is the entire hierarchy a registry object?

Good question, probably yes based on the definition above. This brings out the distinction between object and resource.

> When an API includes sub-resources in its data field, is each sub-resource a registry object?

I would say no, because I think that would require us to put redundant `apiVersion` and `kind` fields in subresources of known type, and that seems tedious for anyone manually creating these files (or reading them).

**Comment by timburks** [comment]
Looking back at this, "Registry YAML" seems like a good way to describe this input format (instead of "Registry Object", "Registry Resource Description", etc.). In the future we might also define "Registry JSON" as the JSON equivalent of Registry YAML. Any objections? If not, I'll update the wiki.

**Comment by seaneganx** [comment]
JSON is already a subset of YAML isn't it? I haven't tried it with our parser. This seems like the type of thing worth noting in docs for awareness, but I think we should continue to generally refer to it as YAML in most cases. Writing YAML/JSON all over the docs would be a bit much IMO.

**Comment by theganyo** [comment]
+1. JSON should work as a subset for ingestion. (For export, however, we may need a JSON option.)

**Comment by timburks** [comment]
I've "promoted this topic" to a dedicated wiki page: https://github.com/apigee/registry/wiki/Registry-YAML.

**Comment by timburks** [comment]
Closing this since it's gotten quiet and we've added notes and documentation links. Feel free to reopen if needed.
